#include "DeferredLighting.hlsli"

cbuffer RenderPassDebugBuffer : register(b5)
{
    uint DebugRenderPass;
    float3 __RenderPassDebugPadding;
}

float3 CalculateLightOnly(float3 aNormal, float3 aWorldPosition, float3 aViewDirection)
{
    // Unreal-style light-only material: neutral matte grey, non-metallic, and
    // fully rough. Material albedo, ORM, emission, and AO are deliberately
    // ignored so only illumination and shadowing remain visible.
    const float3 diffuse = float3(0.5f, 0.5f, 0.5f);
    const float3 specular = float3(0.04f, 0.04f, 0.04f);
    const float roughness = 1.0f;

    float3 radiance = CalculateAmbientIBL(diffuse, specular, roughness, aNormal, aViewDirection, 1.0f);

    // This must remain statically bounded: the runtime compiler promotes the
    // gradient warning generated by a variable-length shadow loop to an error.
    [unroll]
    for (uint lightIndex = 0; lightIndex < MAX_LIGHTS; ++lightIndex)
    {
        if (lightIndex >= LB_NumActiveLights)
            continue;

        const Light light = LB_Lights[lightIndex];
        if (light.Type == LIGHT_TYPE_DIRECTIONAL)
        {
            radiance += CalculateDirectionalLight(light, diffuse, specular, roughness, aNormal, aViewDirection)
                * CalculateDirectionalShadow(light, aWorldPosition);
        }
        else if (light.Type == LIGHT_TYPE_POINT)
        {
            radiance += CalculatePointLight(light, diffuse, specular, roughness, aNormal, aWorldPosition, aViewDirection)
                * CalculatePointShadow(light, aWorldPosition);
        }
        else if (light.Type == LIGHT_TYPE_SPOT)
        {
            radiance += CalculateSpotLight(light, diffuse, specular, roughness, aNormal, aWorldPosition, aViewDirection)
                * CalculateSpotShadow(light, aWorldPosition);
        }
    }

    return radiance;
}

float4 main(FullTextureVertex aPixel) : SV_TARGET
{
    const float4 albedo = GBufferAlbedo.Sample(TrilinearClamp, aPixel.UV);
    if (albedo.a == 0.0f)
        return 0.0f;

    const float3 material = GBufferSurface.Sample(TrilinearClamp, aPixel.UV).rgb;
    float3 result = 0.0f;

    // RenderPass values are deliberately stable because the label and shortcut
    // are exposed to users in every build configuration.
    if (DebugRenderPass == 1)          result = pow(saturate(albedo.rgb), 1.0f / 2.2f); // Albedo, sRGB
    else if (DebugRenderPass == 2)     result = material.ggg;                            // Roughness, linear
    else if (DebugRenderPass == 3)     result = material.bbb;                            // Metalness, linear
    else if (DebugRenderPass == 4)     result = material.rrr;                            // Texture AO, linear
    else if (DebugRenderPass == 5)     result = ScreenSpaceAO.Sample(TrilinearClamp, aPixel.UV).rrr;
    // The compact GBuffer does not retain a tangent basis. Keep the debugger
    // usable by showing the calculated pixel normal for this legacy view.
    else if (DebugRenderPass == 6)     result = GBufferNormal.Sample(TrilinearClamp, aPixel.UV).xyz * 0.5f + 0.5f;
    else if (DebugRenderPass == 7)     result = GBufferNormal.Sample(TrilinearClamp, aPixel.UV).xyz * 0.5f + 0.5f;
    else if (DebugRenderPass == 8)
    {
        const float3 normal = normalize(GBufferNormal.Sample(TrilinearClamp, aPixel.UV).xyz);
        const float3 position = GBufferWorldPosition.Sample(TrilinearClamp, aPixel.UV).xyz;
        const float3 viewDirection = normalize(FB_CameraPosition - position);
        result = pow(abs(CalculateLightOnly(normal, position, viewDirection)), 1.0f / 2.2f);
    }

    return float4(result, 1.0f);
}
